# [START runtime]
runtime: python
entrypoint: gunicorn -b :$PORT remia.wsgi
env: flex

beta_settings:
# from command >> gcloud sql instances describe DATABASE-NAME <<
  cloud_sql_instances: 'remia012:europe-west4:remiaclients'

runtime_config:
  python_version: 3
# [END runtime]

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10