# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Volledige naam', max_length=50)),
                ('street_and_number', models.CharField(help_text='Straat + Huisnummer', max_length=300)),
                ('postcode', models.CharField(help_text='Postcode', max_length=20)),
                ('city', models.CharField(help_text='Plaats', max_length=200)),
            ],
        ),
    ]
