# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-17 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shippings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='origin',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
